#!/bin/sh

set -e

export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/"$(id -u)"
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"

update_status(){
	capacity="$(cat /sys/class/power_supply/BAT0/capacity)"
	charging_status="$(cat /sys/class/power_supply/BAT0/status)"
}

handle_low_power(){
	if [ "$charging_status" != 'Discharging' ];then
		return
	fi

	if [ "$capacity" -gt '25' ]; then
		return
	fi

	notify-send 'Battery low' -u critical
}

main(){
	update_status
	handle_low_power
}

main "${@}"
