#!/bin/sh

set -e

BATTERY_LOW_FILE='/tmp/check-battery_low.tmp'
BATTERY_LOW_PERCENTAGE='25'
BATTERY_CRITICAL_PERCENTAGE='10'

export DISPLAY=':0'
export XDG_RUNTIME_DIR=/run/user/"$(id -u)"
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"

update_status(){
	capacity="$(cat /sys/class/power_supply/BAT0/capacity)"
	charging_status="$(cat /sys/class/power_supply/AC/online)"
}

handle_high_power(){
	if [ "${capacity}" -le "${BATTERY_LOW_PERCENTAGE}" ]; then
		return
	fi

	rm -f "${BATTERY_LOW_FILE}"
}

handle_low_power(){
	if [ "${charging_status}" -eq '1' ];then
		return
	fi

	if [ "${capacity}" -gt "${BATTERY_LOW_PERCENTAGE}" ]; then
		return
	fi

	if [ -f "${BATTERY_LOW_FILE}" ]; then
		return
	fi

	touch "${BATTERY_LOW_FILE}"

	notify-send 'Battery' 'Power low' -u critical
}

handle_critical_power(){
	if [ "${charging_status}" -eq '1' ];then
		return
	fi

	if [ "${capacity}" -gt "${BATTERY_CRITICAL_PERCENTAGE}" ]; then
		return
	fi

	notify-send 'Battery' 'Power critical' -u critical
}

main(){
	update_status

	handle_high_power

	handle_low_power

	handle_critical_power
}

main "${@}"
