#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Select a script through dmenu

script="$(\
	cat <<- EOF | dmenu -i -l 10
	toggle-compositor
	toggle-night-light
	toggle-eq
	toggle-screenkey
	weather
EOF
)"

"$script"
