#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Emoji selector

set -eu

DMENU_BIN=
COPY_BIN=

options=$(\
	cat <<-'EOF'
		(⌐■_■), Lenny
		( ͡° ͜ʖ ͡°), Lenny
		¯\_(ツ)_/¯, Lenny
		(˵ ͡° ͜ʖ ͡°˵), Lenny
		(╯°□°）╯︵ ┻━┻, Lenny
		( ͡° ͡° ͡° ͜ʖ ͡° ͡° ͡°), Lenny
		 ̿ ̿'̿'\̵͇̿̿\з=(•_•)=ε/̵͇̿̿/'̿'̿ ̿, Lenny
	EOF
)

case "${XDG_SESSION_TYPE}" in
	'x11')
		DMENU_BIN='dmenu'
		COPY_BIN='xclip -selection clipboard'
		;;
	'wayland')
		DMENU_BIN='wmenu'
		COPY_BIN='wl-copy'
		;;
	*) return;;
esac

choice="$(\
	printf '%s' "${options}" | \
	${DMENU_BIN} -p 'Type Emoji name' -i -l 10 | \
	cut -d ',' -f 1
)"

if [ -z "${choice}" ]; then
	return
fi

printf '%s' "${choice}" | ${COPY_BIN}

notify-send 'emoji-menu' "${choice}"
