#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Run command inside lxc container

set -e

CONTAINER_NAME='dev'
CONTAINER_USER_NAME='dev'
WORKDIR="$(pwd)"
COMMANDS="${@}"

mount_disk(){
	incus config device add \
		"${CONTAINER_NAME}" "${WORKDIR}" disk \
		source="${WORKDIR}" \
		path="/mnt${WORKDIR}" \
		shift=true \
		--quiet
}

run_command(){
	incus exec "${CONTAINER_NAME}" -- \
		su --pty \
		--login "${CONTAINER_USER_NAME}" \
		--command "${COMMANDS}"
}

unmount_disk(){
	incus config device remove \
		"${CONTAINER_NAME}" "${WORKDIR}" \
		--quiet
}

main(){
	# mount_disk
	run_command
}

main "${0}"

# trap 'unmount_disk' EXIT INT QUIT TERM HUP
