#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Make directories and files private

set -e

main(){
	owner="${1}"
	path="${2}"

	chown --recursive "${owner}" "${path}"
	chmod --recursive o-rwx "${path}"
	chmod --recursive g-rwx "${path}"
	setfacl --recursive --default --modify g::-,o::- "${path}"
}

main "${@}"
