#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Open rss link

# Set script name
NAME="$(basename $0)"

check_arguments(){
	# Check arguments
	if [ -z "$1" ]; then
		printf "Usage: $NAME <link>" >&2
		exit 1
	fi
}

prepare_browser(){
	# Set correct browser
	if [ "$PRIVATE_BROWSER" ]; then
		browser="$PRIVATE_BROWSER"
		return
	fi

	if [ "$BROWSER" ]; then
		browser="$BROWSER"
		return
	fi

	browser="$(basename $(xdg-mime query default text/html) .desktop)"
}

open_video(){
	open-video-link "$1" >/dev/null 2>&1 &
}

open_browser(){
	# Open using window manager if available
	if ! which i3 >/dev/null 2>&1; then
		"$browser" -- "$1" >/dev/null 2>&1 &
		return
	fi

	i3-msg "exec --no-startup-id $browser $1" >/dev/null 2>&1 &
}

run(){
	case "$1" in
		*youtube.com/watch\?v=*) open_video "$1";;
		*odysee.com/@*/*) open_video "$1";;
		*) open_browser "$1";;
	esac
}

main(){
	check_arguments "$@"
	prepare_browser "$@"
	run "$@"
}

main "$@"
