#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Reset Stapm for AMD mobile APUs

set -e
NAME="$(basename "$0")"

STAPM_TIME='500'
SLOW_TIME='30'
STAPM_LIMIT_MIN='10000'
SLOW_LIMIT_MIN='10000'
STAPM_LIMIT_MAX='15000'
SLOW_LIMIT_MAX='25000'
SLEEP_TIME='30'

print_error(){
	message="$1"
	echo "${NAME} - Error: ${message}" >&2
}

check_root(){
	if [ "$(id -u)" -ne '0' ]; then
		print_error 'Please run as root.'
		return 1
	fi
}

run(){
	ryzenadj --stapm-time="${STAPM_TIME}" --slow-time="${STAPM_TIME}" --max-performance

	while true; do
		ryzenadj --stapm-limit="${STAPM_LIMIT_MIN}" --slow-limit="${SLOW_LIMIT_MIN}" && \
			ryzenadj --stapm-limit="${STAPM_LIMIT_MAX}" --slow-limit="${SLOW_LIMIT_MAX}"

		sleep "${SLEEP_TIME}"
	done
}

main(){
	check_root
	run
}

main "$@"
