#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Toggle night light

if pgrep redshift; then
	redshift -x
	pkill redshift
	notify-send 'Night Light' 'off'
	return
fi

redshift &
notify-send 'Night Light' 'on'
