#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Change keyboard layout

# Prepare
MAIN_LAYOUT=eu
SEC_LAYOUT=ara

if setxkbmap -query | grep -q "^layout:\s*$MAIN_LAYOUT"; then
	setxkbmap -layout $SEC_LAYOUT
	notify-send 'Keyboard Layout' "${SEC_LAYOUT}"
	return
fi

setxkbmap -layout $MAIN_LAYOUT
notify-send 'Keyboard Layout' "${MAIN_LAYOUT}"
