#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Change keyboard layout

set -e

main(){
	lang_choice="$( \
		cat <<-'EOF' | dmenu -p 'Choose language' -i -l 10
			eu
			ara
			jp
		EOF
	)"

	setxkbmap -layout "${lang_choice}"
	notify-send 'Keyboard Layout' "${lang_choice}"
}

main "${@}"
