#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Toggle screenkey

if pgrep screenkey; then
	pkill screenkey
	notify-send 'Screenkey' 'off'
	return
fi

screenkey --font-size small --opacity 0.5 --persist --compr-cnt 1 &
notify-send 'Screenkey' 'on'
