#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Toggle audio EQ

if pgrep -x easyeffects; then
	pkill easyeffects
	return
fi

easyeffects --gapplication-service
