#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Toggle audio EQ

if pgrep -x easyeffects; then
	pkill easyeffects
	notify-send 'EQ' 'off'
	return
fi

easyeffects --gapplication-service &
notify-send 'EQ' 'on'
