#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Toggle audio EQ

if pgrep -x easyeffects; then
	easyeffects -q
	pkill easyeffects
	notify-send 'EQ' 'off'
	return
fi

flatpak run com.github.wwmm.easyeffects --gapplication-service &
notify-send 'EQ' 'on'
