#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Check weather

set -e
WEATHER_SERVICE_URL='https://wttr.in'

get_locaiton(){
	if [ -z "${DISPLAY}" ]; then
		read -r location
		return
	fi

	location="$(printf '' | dmenu -p 'Enter location' -i -l 5)"
}

run(){
	curl -L "${WEATHER_SERVICE_URL}/${location}?n"
}

main(){
	get_locaiton
	run
}

main "$@"
